version: 2
models:
  - name: stg_listening_history
    columns:
      - name: track_id
        tests: [not_null]
      - name: played_at
        tests: [not_null]
  - name: stg_audio_features
    columns:
      - name: track_id
        tests: [unique, not_null]
      - name: danceability
        tests: [{dbt_utils.accepted_range: {min_value: 0, max_value: 1}}]
      - name: energy
        tests: [{dbt_utils.accepted_range: {min_value: 0, max_value: 1}}]
      - name: valence
        tests: [{dbt_utils.accepted_range: {min_value: 0, max_value: 1}}]
